### ISSUE TITLE
查询不了国际服的抽卡记录

### ISSUE THREAD

**Issue by AHpxChina** [biuuu/genshin-gacha-export#1]
我首先查询的国服的抽卡记录，能够正常使用。
但是当我打开国际服的抽卡记录时，单击"更新数据"按钮，得到的仍然是国服的抽卡记录。

**Comment by biuuu** [comment]
两者同时存在时会优先取国服记录，
可以暂时删掉 `C:\Users\{用户名}\AppData\LocalLow\miHoYo\原神\output_log.txt` 文件，
这样就会取外服的记录了。

**Comment by fj211314** [comment]
请问一下 我是美服的 ,删掉output_log文件以后 ,显示未找到url 造作失败,  请问有什么办法么?
