### ISSUE TITLE
饼图在显示0数据时没有正常表示实际的比率

### ISSUE THREAD

**Issue by HeroTch** [biuuu/genshin-gacha-export#11]
![image](https://i0.hdslb.com/bfs/album/2cb35ebf8bbfe3759ef43ee7a801bdda9624cda1.jpg)
武器池抽了1发的情况，没有五星武器却在饼图上仍有体现

**Comment by biuuu** [comment]
是换账号更新后出现的吗？用的哪个版本

**Comment by HeroTch** [comment]
就是全新使用，0.0.8版本

**Comment by biuuu** [comment]
截图的版本应该不是0.0.8哦，新版本5星武器那里角度不是90度垂直的
![image](https://user-images.githubusercontent.com/10892119/108589900-b775ae00-739b-11eb-9489-0ff4e64d9eb5.png)
