### ISSUE TITLE
老哥，yarn dev  页面报错require is not defined

### ISSUE THREAD

**Issue by ylygithub** [biuuu/genshin-gacha-export#12]
这是为啥

**Comment by biuuu** [comment]
是用浏览器打开出现的吗？
这页面只能用electron加载的

**Comment by ylygithub** [comment]
> 是用浏览器打开出现的吗？
> 这页面只能用electron加载的

浏览器没有node环境
嗯 ，electron 可以 ，浏览器不能调试吗？ 我看文档不是写了nodeIntegration = true吗

**Comment by biuuu** [comment]
electron的模块似乎没法用vite的import导入，你改下可以试试，我没找到解决办法就改成require了

**Comment by ylygithub** [comment]
昨天 试了不得行 好吧 谢了 老哥
