### ISSUE TITLE
Novice Wishes are not being exported into excel / 新手愿望未导出到Excel

### ISSUE THREAD

**Issue by CT4nk3r** [biuuu/genshin-gacha-export#13]
For some reason my novice wishes are not exported into the excel table, everything else works fine.
Also in the international version of the game, there are no graphs.

由于某种原因，我的新手愿望没有导出到excel表中，其他所有工作都很好。
在游戏的国际版本中，也没有图表。

Sorry for using google translate, hope it is understandable.

**Comment by biuuu** [comment]
It should be because it is not compatible with other game languages, and it will be updated later.
It’s okay, I also use Google Translate.

**Comment by biuuu** [comment]
I tried the game language in English, and it’s true there are no charts, but novice wishes can be exported to excel.

**Comment by CT4nk3r** [comment]
I was able to fix the novice one with a restart thankfully, hope the charts are going to be added in the future, still nice work, love the app!

**Comment by biuuu** [comment]
In the latest version, the chart can be displayed normally, but the localization of the UI has not been completed.
