### ISSUE TITLE
欧服按操作导出抽卡数据，显示为authkey timeout 操作失败

### ISSUE THREAD

**Issue by mu-yu-li** [biuuu/genshin-gacha-export#15]
欧服玩家，按操作首先打开up池历史记录，而后打开导出工具，点击导出，显示“authkey timeout 操作失败”

**Comment by biuuu** [comment]
上次游戏里看记录的时间隔太久，超时了。重新在游戏里打开一遍记录就可以了。

**Comment by mu-yu-li** [comment]
> 上次游戏里看记录的时间隔太久，超时了。重新在游戏里打开一遍记录就可以了。

试着很快打开来试了一下，还是不行，一样的错误。

**Comment by mu-yu-li** [comment]
啊，是否可能是我本机同时安装了国服和外服的问题？请问有办法解决吗，我只需要外服的。

**Comment by biuuu** [comment]
`C:\Users{用户名}\AppData\LocalLow\miHoYo\原神\output_log.txt`
删除这个文件

**Comment by mu-yu-li** [comment]
> `C:\Users{用户名}\AppData\LocalLow\miHoYo\原神\output_log.txt`
> 删除这个文件

感谢！成功了！
