### ISSUE TITLE
Translation of the application into Russian.

### ISSUE THREAD

**Issue by toxicfusi0n** [biuuu/genshin-gacha-export#17]
um, I hope this reaches the creator. I would like to add "russian language" support to this application. as I am not a programmer, I can provide the exact translation of all the words.

**Comment by biuuu** [comment]
Thank you support.
I have plans to add i18n, it may take a few days.

**Comment by toxicfusi0n** [comment]
> Thank you for your support.
> I have plans to add i18n, it may take a few days.

Wow, I will definitely be waiting!

**Comment by biuuu** [comment]
https://github.com/biuuu/genshin-gacha-export/blob/dev/src/i18n/P%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9.json
The text has been sorted out, but the function is not yet complete.
You can translate at any time.

**Comment by toxicfusi0n** [comment]
> https://github.com/biuuu/genshin-gacha-export/blob/dev/src/i18n/P%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9.json
> The text has been sorted out, but the function is not yet complete.
> You can translate at any time.

I'll do it soon

**Comment by biuuu** [comment]
https://github.com/biuuu/genshin-gacha-export/releases
Version 0.4.0 can see the translation.
