### ISSUE TITLE
求问大佬的调用URL是怎么得到的

### ISSUE THREAD

**Issue by brendansun93** [biuuu/genshin-gacha-export#18]
大佬问一下，你这个调用的地址是怎么得到的？我看了output log半天也没看出哪里。
谢谢大佬。

**Comment by biuuu** [comment]
游戏里打开记录才会有，这可能只是一个BUG，说不定很快就被修复了。

**Comment by brendansun93** [comment]
大佬我想问的是，那个获取抽卡信息的API接口是怎么知道的，能分享么？

**Comment by biuuu** [comment]
找个抓包工具看
