### ISSUE TITLE
lzma-native安装时间好长啊

### ISSUE THREAD

**Issue by dtyctrl** [biuuu/genshin-gacha-export#21]
如题，这个包安装时间好长，这样正常吗，我把yarn改成了国内淘宝源也是巨慢

**Comment by biuuu** [comment]
没遇到这种情况，是windows吗

**Comment by biuuu** [comment]
改yarn源的话，可能要删掉yarn.lock才有用

**Comment by dtyctrl** [comment]
是windows，yarn.lock是锁package.json里依赖的，切源应该是下载时用的yarn的服务不同，这个应该不会影响不

**Comment by biuuu** [comment]
应该是锁下载地址的
