### ISSUE TITLE
我修改了一下开发流程和打包流程，不知道大佬。。。喜不喜欢这样

### ISSUE THREAD

**Issue by umbrella22** [biuuu/genshin-gacha-export#22]
我现在将主进程和渲染进程文件夹分开了，并且添加了开发时对主进程的打包和更新检测：
**但是改动挺大的，文件夹位置全都换掉了，也加了不少开发时的依赖**
## 已做的修改
- 当修改了主进程文件时，rollup检测到文件变动就会自动编译主进程并重启应用更新
- 当打包之后，主进程和渲染进程均为生产环境状态，不再以源码文件目录的形式暴漏出去
- 使用electron-builder进行打包操作，emm，怎么说呢，会生成安装文件了，并且压缩后就是大概50m的大小，也可以让用户指定安装位置之类的这些。。。。
## 尚未完成的修改
- 您的渲染进程增量更新我还在修改，但是应该很快就会完成了（毕竟不用动啥。。。。就是改一下路径，逃~

**Comment by biuuu** [comment]
我觉得挺好的，
不过没有签名，打包成安装文件会不会更容易被拦截

**Comment by umbrella22** [comment]
emm，不考虑360的话，萌大奶，不过也可以不打包成安装文件，也可以只创建zip这类的，builder蛮灵活的

**Comment by umbrella22** [comment]
我已经提交了一份pr，做的变更在pr那边我都写了一下，应该没有啥遗漏了。。。。。大概，大佬的代码学习起来挺舒服的~

**Comment by biuuu** [comment]
@umbrella22 
这个自动重启应用体验不太好啊，我是设置成编辑器自动保存的。
写一句就得重启一下

**Comment by umbrella22** [comment]
@biuuu 是这样的。。。emm，我后面看看可不可以做到hmr，webpack那边实现了，但是rollup的话。。。。。。害我是手动保存代码还真没注意到这个细节。。。但是也是只有在写主进程时候，会这样来着，渲染进程可能并不会。。。
