### ISSUE TITLE
0.0.7版出現兩個同樣的圖表

### ISSUE THREAD

**Issue by NeiL978** [biuuu/genshin-gacha-export#3]
![image](https://user-images.githubusercontent.com/19291616/108161894-efc08680-7126-11eb-8a28-ed8c9b6e0196.png)

**Comment by biuuu** [comment]
这是在简体和繁体语言下分别获取的数据吗

**Comment by NeiL978** [comment]
都是在繁體語系下獲取的
現在解決了
我把C:\Users使用者帳號\AppData\Roaming\genshin-gacha-export-electron
\Genshin-Gacha-Export \resources\app\userData和\Genshin-Gacha-Export \resources\app\src\userData
所有裡面的兩個json檔案(gacha-list.json和gacha-list-802XXXXXX.json)刪除
讓他重新抓資料就剩下一筆了
我之前用0.0.5版本後直接用0.0.7版
