### ISSUE TITLE
Microsoft defender report

### ISSUE THREAD

**Issue by Haku247** [biuuu/genshin-gacha-export#31]
![image](https://user-images.githubusercontent.com/20238213/110190762-3ec92400-7e68-11eb-8b80-8c4352de445c.png)

**Comment by biuuu** [comment]
确认是从这里下载的吗，文件名大小写不同

**Comment by Haku247** [comment]
> 确认是从这里下载的吗，文件名大小写不同

不好意思我刚看了一下。。是这个项目的上游项目，之前导出抽卡的那个命令行程序的问题。
