### ISSUE TITLE
Missing 4-star character in weapon event wish

### ISSUE THREAD

**Issue by ntuan2502** [biuuu/genshin-gacha-export#32]
![image](https://user-images.githubusercontent.com/44097595/110196655-94a5c800-7e78-11eb-81c6-868c6e087fc4.png)

In the wish weapon event chart, the 4-star character is currently missing. Can you re-add it? Thanks!

**Comment by biuuu** [comment]
Is it possible that you don’t have a 4-star character in your record?

**Comment by ntuan2502** [comment]
ah, I got it :))
