### ISSUE TITLE
更新数据时获取到已有的数据可以停止获取以减轻米忽悠服务器的压力

### ISSUE THREAD

**Issue by Redlnn** [biuuu/genshin-gacha-export#34]
目前每次更新数据都会把所有页面加载一遍，用的人多了可能会对米忽悠的服务器产生较大的压力，促使米忽悠加入反制手段。

可以在更新数据时与本地已有数据进行匹配，比如角色祈愿第5页的最后3条数据跟本地数据吻合，就不用继续获取后面几页

**Comment by biuuu** [comment]
已支持

**Comment by Redlnn** [comment]
厉害了，效率好高，感谢作者写的这么好用的软件
