### ISSUE TITLE
国外用户无法使用

### ISSUE THREAD

**Issue by ZHUYUEHAN1** [biuuu/genshin-gacha-export#6]
点击更新数据之后一直显示

正在获取角色活动祈愿第X页

毫无进展

人在日本 开的国服

**Comment by MoonCocoon** [comment]
可以用的，你试试把界面设成中文的。我设的繁体中文都可以用，欧服

**Comment by MoonCocoon** [comment]
而且如果第一次没读出来，强退了再试一次
