### ISSUE TITLE
本地源码运行无内容

### ISSUE THREAD

**Issue by KveinAxel** [biuuu/genshin-gacha-export#7]
本地yarn install完毕后yarn start在electron里面只有一片空白
![image](https://user-images.githubusercontent.com/41867249/108237697-1f04e100-7183-11eb-9700-9596a555d16b.png)

**Comment by KveinAxel** [comment]
这是运行日志
![image](https://user-images.githubusercontent.com/41867249/108238267-bec26f00-7183-11eb-972b-e83621c10728.png)

**Comment by biuuu** [comment]
需要先启动 vite ，
另外开个命令行运行 `yarn dev`
