### ISSUE TITLE
查询国际服记录时提示“未找到URL”

### ISSUE THREAD

**Issue by AZTO233** [biuuu/genshin-gacha-export#8]
是美服，重启游戏和软件仍然会提示“未找到URL-操作失败”，没有安装国服。

难道是非酋连抽卡统计记录都不配看吗？ :(

**Comment by biuuu** [comment]
C:\Users\{用户名}\AppData\LocalLow\miHoYo\原神\output_log.txt
看你是否有这个文件，有的话删掉再试

**Comment by IncinerateZ** [comment]
To fix open wish history in game every time you re-launch game.

**Comment by LuminaRein** [comment]
同时安装了美服和国服好像也只能显示国服的数据，请问有什么解决方法吗？

**Comment by biuuu** [comment]
> 同时安装了美服和国服好像也只能显示国服的数据，请问有什么解决方法吗？

C:\Users{用户名}\AppData\LocalLow\miHoYo\原神\output_log.txt
看你是否有这个文件，有的话删掉再试
